# Generated by Django 4.2.2 on 2023-06-27 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_addroom'),
    ]

    operations = [
        migrations.CreateModel(
            name='room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(max_length=2000, upload_to='')),
                ('room_name', models.CharField(max_length=200)),
                ('details', models.TextField()),
                ('cost', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='addroom',
        ),
        migrations.DeleteModel(
            name='booking',
        ),
    ]
