# Generated by Django 4.2.2 on 2023-06-27 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_room_delete_addroom_delete_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='image',
            field=models.ImageField(max_length=5000, upload_to=''),
        ),
    ]
