# Generated by Django 4.2.2 on 2023-06-28 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_roombooking_delete_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=100)),
                ('message', models.TextField()),
            ],
        ),
    ]
